# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Builder stage
FROM node:lts-alpine AS builder
WORKDIR /app

# Copy project files
COPY package.json tsconfig.json ./
COPY src ./src

# Install dependencies, build TypeScript, and prune dev dependencies
RUN npm install && \
    npm run build && \
    npm prune --production

# Final image
FROM node:lts-alpine
WORKDIR /app

# Copy built files and production dependencies
COPY --from=builder /app/build ./build
COPY --from=builder /app/node_modules ./node_modules

ENV NODE_ENV=production

# Expose stdio (no ports) and run the MCP server
CMD ["node", "build/index.js"]
